# Initial idea of repoman checks: https://github.com/mrueg/repoman-travis

dist: xenial
sudo: required
language: generic
services:
    - docker

git:
    depth: 1
branches:
    only:
        - 'master'
        - '/^dev\//'
        - '/^ci\//'

## env config and env-based matrix
env:
    global:
        ## configurable variables
        - 'DOCKER_REPO=rindeal/portage-amd64-base'
        - 'DOCKER_TAG=latest'

## final touches to the matrix
matrix:
    fast_finish: true

# -----------------------------------------------------------------------------

install:
    - 'docker pull "${DOCKER_REPO}:${DOCKER_TAG}"'

script:
    - '.travis/script.sh "${DOCKER_REPO}" "${DOCKER_TAG}"'

# after_success:
#     - cd "${TRAVIS_BUILD_DIR}"
#     - .travis/setup_git.sh

# -----------------------------------------------------------------------------

notifications:
  email: false
  webhooks:
    - https://fathomless-fjord-24024.herokuapp.com/notify
